const sharedDocumentHead = `
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <style>
    /* Reset basic styles */
    html, body {
      margin: 0;
      padding: 0;
      background: transparent;
    }
    
    /* 
      Override viewport-locking styles often generated by LLMs.
      Map viewport height to a sensible default inside the iframe 
      so flex layouts and canvas charts don't collapse or expand infinitely.
    */
    .h-screen, .h-\\[100vh\\] {
      height: 600px !important;
    }
    .min-h-screen, .min-h-\\[100vh\\] {
      min-height: 600px !important;
    }
    canvas {
      max-height: 600px !important;
    }
  </style>
`;

export function buildIframeHTML(code: string, renderType: 'html' | 'react', frameId: string): string {
  const sizeReporterScript = buildSizeReporterScript(frameId);

  if (renderType === 'html') {
    return wrapHTMLDocument(code, sizeReporterScript);
  }

  return `<!DOCTYPE html>
<html>
<head>
  ${sharedDocumentHead}
  <script src="https://cdn.tailwindcss.com"><\/script>
  <script src="https://unpkg.com/react@18/umd/react.production.min.js"><\/script>
  <script src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"><\/script>
  <script src="https://unpkg.com/@babel/standalone/babel.min.js"><\/script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.4.1/chart.umd.js"><\/script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"><\/script>
</head>
<body>
  <div id="root"></div>
  <script type="text/babel">
    ${code}
    ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(App));
  <\/script>
  ${sizeReporterScript}
</body>
</html>`;
}

function wrapHTMLDocument(code: string, sizeReporterScript: string): string {
  if (/<html[\s>]/i.test(code)) {
    let wrapped = code;

    if (/<head[^>]*>/i.test(wrapped)) {
      wrapped = wrapped.replace(/<head([^>]*)>/i, `<head$1>${sharedDocumentHead}`);
    } else {
      wrapped = wrapped.replace(/<html([^>]*)>/i, `<html$1><head>${sharedDocumentHead}</head>`);
    }

    wrapped = wrapped.replace(
      /<body([^>]*)>/i,
      (_match, attrs: string) => `<body${attrs} style="margin:0;padding:0;background:transparent;overflow:visible;">`
    );

    if (/<\/body>/i.test(wrapped)) {
      wrapped = wrapped.replace(/<\/body>/i, `${sizeReporterScript}</body>`);
    } else {
      wrapped += sizeReporterScript;
    }

    return wrapped;
  }

  return `<!DOCTYPE html>
<html>
<head>
  ${sharedDocumentHead}
</head>
<body>
  ${code}
  ${sizeReporterScript}
</body>
</html>`;
}

function buildSizeReporterScript(frameId: string): string {
  return `<script>
    (() => {
      const frameId = ${JSON.stringify(frameId)};
      let rafId = 0;

      const reportSize = () => {
        const body = document.body;
        const html = document.documentElement;
        if (!body || !html) return;

        const width = Math.max(body.scrollWidth, body.offsetWidth, html.scrollWidth, html.offsetWidth);
        const height = Math.max(body.scrollHeight, body.offsetHeight, html.scrollHeight, html.offsetHeight);

        parent.postMessage({
          source: 'visualmind-iframe-size',
          frameId,
          width,
          height
        }, '*');
      };

      const scheduleReport = () => {
        cancelAnimationFrame(rafId);
        rafId = requestAnimationFrame(reportSize);
      };

      window.addEventListener('load', scheduleReport);
      window.addEventListener('resize', scheduleReport);
      document.addEventListener('DOMContentLoaded', scheduleReport);

      if (window.ResizeObserver) {
        const resizeObserver = new ResizeObserver(scheduleReport);
        resizeObserver.observe(document.documentElement);
        if (document.body) resizeObserver.observe(document.body);
      }

      if (window.MutationObserver) {
        const mutationObserver = new MutationObserver(scheduleReport);
        mutationObserver.observe(document.documentElement, {
          childList: true,
          subtree: true,
          attributes: true,
          characterData: true
        });
      }

      [0, 60, 180, 400, 900, 1600].forEach((delay) => {
        setTimeout(scheduleReport, delay);
      });
    })();
  <\/script>`;
}

export function renderToIframe(iframe: HTMLIFrameElement, code: string, renderType: 'html' | 'react', frameId: string) {
  iframe.srcdoc = buildIframeHTML(code, renderType, frameId);
}
